# Generated by Django 3.2.7 on 2022-02-08 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_loanform_userform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanform',
            name='phno',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
