# Generated by Django 3.2.7 on 2022-02-09 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_loanform_phno'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanform',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='loanform',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
